sudo: required
language: go
go:
- 1.10.1

services:
- docker

install:
- docker pull therecipe/qt:linux
- docker pull therecipe/qt:rpi1
- docker pull therecipe/qt:rpi2
- docker pull therecipe/qt:rpi3
- go get -u -v github.com/therecipe/qt/cmd/...

script:
- $GOPATH/bin/qtdeploy -docker build linux
- $GOPATH/bin/qtdeploy -docker build rpi1
- $GOPATH/bin/qtdeploy -docker build rpi2
- $GOPATH/bin/qtdeploy -docker build rpi3