sudo: required
language: go
go:
- 1.11.1

services:
- docker

install:
- docker pull therecipe/qt:android
- go get -v -tags=no_env github.com/therecipe/qt/cmd/...

script:
- $GOPATH/bin/qtdeploy -docker build android
- $GOPATH/bin/qtdeploy -docker build android-emulator